export const datosChat = [
  // --- SOCIAL ---
  { 
    id: "saludo", 
    categoria: "general", 
    palabrasClave: ["hola", "inicio", "buenas"], 
    tipo: "social", 
    definicion: "¡Hola! 👋 Base de Datos Maestra Cargada.\n\nHe restaurado las definiciones teóricas completas.\n\nSelecciona una tecnología:\n1. Java ☕\n2. Python 🐍\n3. C++ 🚀\n4. HTML 🌐", 
    pista: "Escribe un lenguaje." 
  },
  { 
    id: "ayuda", 
    categoria: "general", 
    palabrasClave: ["ayuda", "temas", "menu", "lista"], 
    tipo: "social", 
    definicion: "📚 Escribe 'temas' dentro de cualquier lenguaje para ver el índice completo.", 
    pista: "Prueba: 'temas' en Python." 
  },

  // =================================================================================
  // ☕ JAVA (INTRODUCCIÓN COMPLETA + TEMAS)
  // =================================================================================
  { 
    id: "java_intro", 
    categoria: "java", 
    nombre: "Introducción a Java", 
    palabrasClave: ["java", "1"], 
    tipo: "concepto", 
    definicion: "☕Java a Fondo – 4ª Edicióndel autor Pablo Augusto Sznajdleder\n\n\n\n ¿QUÉ ES JAVA?\n\n El lenguaje Java es un lenguaje de programación diseñado para desarrollar aplicaciones completas y escalables. No solo permite escribir programas, sino también diseñar sistemas de software estructurados, utilizando principios de ingeniería de software y programación orientada a objetos.\n\nCaracterísticas Clave:\n\n• Orientado a Objetos: \n Esto significa que los programas se organizan en clases y objetos que representan entidades del mundo real.\n\n• Multiplataforma: \n Esto significa que un programa escrito en Java puede ejecutarse en diferentes sistemas operativos como: Windows, macOS y Linux.\n\n• Lenguaje compilado e interpretado:\nJava utiliza un proceso especial de ejecución. \n\n• Seguridad. \n Java fue diseñado con mecanismos de seguridad que ayudan a evitar errores o accesos indebidos al sistema Java fue diseñado con mecanismos de seguridad que ayudan a evitar errores o accesos indebidos al sistema.\n\nUsos: \nJava es ampliamente utilizado en el desarrollo de aplicaciones empresariales, aplicaciones móviles (Android), sistemas embebidos y aplicaciones web (Spring).", 
        codigos: [
      {titulo: "Hola Mundo", cuerpo: "System.out.println(\"Hola\");", explicacion: "🔍 DESGLOSE DETALLADO:\n• System: Clase del sistema.\n• out: Flujo de salida.\n• println: Imprime y salta línea."},
      {titulo: "Estructura Main", cuerpo: "public static void main(String[] a)", explicacion: "🔍 DESGLOSE DETALLADO:\n• public: es un modificador de acceso: Significa que el método puede ser accedido desde cualquier parte del programa.\n• static: indica que el método pertenece a la clase y no a un objeto: Esto significa que no es necesario crear un objeto de la clase para ejecutar el método.\n• void: indica el tipo de valor que devuelve el método: Cuando un método es void, significa que no devuelve ningún valor."}
    ] 
  },
  { id: "j_int", categoria: "java", nombre: "int (Entero)", palabrasClave: ["int"], tipo: "tecnico", definicion: "Entero de 32 bits.", codigos: [{titulo: "Declaración", cuerpo: "int edad = 25;", explicacion: "🔍 DESGLOSE DETALLADO:\n• int: Reserva 32 bits.\n• =: Asignación."}, {titulo: "Suma", cuerpo: "int x = 10 + 5;", explicacion: "🔍 DESGLOSE DETALLADO:\n• int es un tipo de dato primitivo utilizado para almacenar números enteros, es decir, números sin decimales."}] },
  { id: "j_array", categoria: "java", nombre: "Array (Arreglo)", palabrasClave: ["array"], tipo: "tecnico", definicion: "Colección de elementos del mismo tipo.", codigos: [{titulo: "Declaración", cuerpo: "int[] numeros = new int[5];", explicacion: "🔍 DESGLOSE DETALLADO:\n• int[]: Define un arreglo de enteros.\n• new int[5]: Reserva espacio para 5 enteros."}, {titulo: "Acceso a Elementos", cuerpo: "public class EjemploArray {\n\n  public static void main(String[] args) {\n\n   int[] numeros = {5, 10, 15, 20};\n\n   for(int i = 0; i < numeros.length; i++) {\n\n     System.out.println(numeros[i]);\n\n   }\n\n  }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Un array en Java es una estructura de datos que permite almacenar varios valores del mismo tipo dentro de una sola variable, organizados mediante índices que comienzan desde 0. Son muy utilizados para manejar colecciones de datos dentro de los programas."}] },
  { id: "j_float", categoria: "java", nombre: "float (Decimal)", palabrasClave: ["float"], tipo: "tecnico", definicion: "Número con decimales.", codigos: [{titulo: "Declaración", cuerpo: "float pi = 3.14f;", explicacion: "🔍 DESGLOSE DETALLADO:\n• float es un tipo de dato primitivo utilizado para almacenar números con decimales, es decir, números que pueden tener una parte fraccionaria."}, {titulo: "Operación", cuerpo: "public class EjemploFloat {\n\n  public static void main(String[] args) {\n\n   float precio = 12.5f;\n\n   float descuento = 2.0f;\n\n   float resultado = precio - descuento;\n\n   System.out.println(\"Precio final: \" + resultado);\n\n  }\n\n};", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo float es un tipo primitivo de Java que se utiliza para almacenar números con decimales. Tiene una precisión simple y ocupa 32 bits de memoria, por lo que es útil para representar valores numéricos con fracciones en distintos tipos de aplicaciones."}] },
  { id: "j_bool", categoria: "java", nombre: "boolean (Lógico)", palabrasClave: ["boolean"], tipo: "tecnico", definicion: "Valor verdadero o falso.", codigos: [{titulo: "Declaración", cuerpo: "public class EjemploBoolean {\n\n  public static void main(String[] args) {\n\n   int numero = 10;\n\n   boolean esMayor = numero > 5;\n\n   System.out.println(esMayor);\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• boolean es un tipo de dato primitivo utilizado para almacenar valores lógicos, es decir, valores que pueden ser verdaderos (true) o falsos (false)."}, {titulo: "Condicional", cuerpo: "boolean tieneEdad = true; \nboolean tienePermiso = false;\n\nif (tieneEdad && tienePermiso) {\n   System.out.println(\"Puede entrar\");\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo boolean es fundamental para el control de flujo en Java, ya que se utiliza en estructuras condicionales como if, while y for para tomar decisiones basadas en condiciones lógicas."}] }, 
  { id: "j_float", categoria: "java", nombre: "double (Decimal de Doble Precisión)", palabrasClave: ["double"], tipo: "tecnico", definicion: "Número con decimales de doble precisión.", codigos: [{titulo: "Declaración", cuerpo: "double num1 = 9.81;\n\ndouble num2 = 3.2;\n\ndouble resultado = num1 + num2;\n\nSystem.out.println(resultado);", explicacion: "🔍 DESGLOSE DETALLADO:\n• double es un tipo de dato primitivo utilizado para almacenar números con decimales de doble precisión, lo que significa que puede representar números con una mayor cantidad de dígitos significativos y un rango más amplio que el tipo float."}, {titulo: "Cálculo", cuerpo: "public class EjemploDouble {\n\n  public static void main(String[] args) {\n\n   double precio = 19.99;\n\n   double impuesto = 3.50;\n\n\n   double total = precio + impuesto;\n\n\n   System.out.println(\"Total a pagar: \" + total);", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo de dato double es un tipo primitivo de Java utilizado para almacenar números decimales con mayor precisión que float. Es muy utilizado en cálculos matemáticos, científicos y financieros dentro de los programas."}] },
  { id: "j_char", categoria: "java", nombre: "char (Carácter)", palabrasClave: ["char"], tipo: "tecnico", definicion: "Un solo carácter Unicode.", codigos: [{titulo: "Declaración", cuerpo: "char letra = 'A';", explicacion: "🔍 DESGLOSE DETALLADO:\n• char es un tipo de dato primitivo utilizado para almacenar un solo carácter, que puede ser una letra, un dígito, un símbolo o cualquier otro carácter definido en el estándar Unicode."}, {titulo: "Uso en Strings", cuerpo: "String palabra = \"Hola\";\nchar primeraLetra = palabra.charAt(0);", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo char es útil para representar caracteres individuales y se utiliza comúnmente en operaciones de manipulación de texto, como acceder a caracteres específicos dentro de una cadena (String) utilizando métodos como charAt()."}] },
  { id: "j_while", categoria: "java", nombre: "while", palabrasClave: ["while"], tipo: "tecnico", definicion: "Bucle While.", codigos: [{titulo: "Estructura Básica", cuerpo: "public class EjemploWhile {\n\n   public static void main(String[] args) {\n\n     int i = 1;\n\n     while (i <= 5) {\n\n        System.out.println(i);\n\n       i++;\n\n     }\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una estructura de control repetitiva que permite ejecutar un bloque de instrucciones mientras una condición sea verdadera."}, {titulo: "DO WHILE", cuerpo: "public class EjemploDoWhile {\n\n   public static void main(String[] args) {\n\n      int numero = 1;\n\n     do {\n\n       System.out.println(numero);\n\n       numero++;\n\n     } while (numero <= 5);\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• La estructura do while es un ciclo de repetición que ejecuta un conjunto de instrucciones al menos una vez y continúa repitiéndose mientras la condición sea verdadera. Se diferencia de while porque la condición se evalúa al final del ciclo."}] },
  { id: "j_if", categoria: "java", nombre: "if / else", palabrasClave: ["if", "else"], tipo: "tecnico", definicion: "Condicional.", codigos: [{titulo: "Si", cuerpo: "if(x > 0) { }", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una instrucción de control que permite que un programa tome decisiones dependiendo de si una condición es verdadera o falsa."}, {titulo: "Si no", cuerpo: "else { }", explicacion: "🔍 DESGLOSE DETALLADO:\n• Se utiliza junto con if para indicar qué debe ocurrir cuando la condición del if es falsa."}, {titulo: "si y no", cuerpo: "if(x > 0) { } else { }", explicacion: "🔍 DESGLOSE DETALLADO:\n• Combina ambas condiciones."}] },
  { id: "j_switch", categoria: "java", nombre: "switch", palabrasClave: ["switch", "case"], tipo: "tecnico", definicion: "Selector.", codigos: [{titulo: "Evaluar", cuerpo: " switch (expresion) {9 \n case valor1:\ninstrucciones;\n break;\n\n case valor2:\n instrucciones;\n break;\n\n default:\n instrucciones;\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• La estructura switch es una instrucción de control de selección múltiple que permite ejecutar diferentes bloques de código dependiendo del valor de una variable o expresión.."}, {titulo: "Caso con menu integrado", cuerpo: "public class EjemploSwitch {\n\nint dia = 3;\nswitch (dia) {\n\ncase 1:\n   system.out.println('Lunes');\n  break;\nncase 2:\n   system.out.println('Martes');\n  break;\nncase 3:\n   system.out.println('Miércoles');\n  break;\nncase 4:\n   system.out.println('Jueves');\n  break;\nncase 5:\n   system.out.println('Viernes');\n  break;\n\ndefault:\n   system.out.println('Fin de semana');\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El programa evalúa el valor de la variable dia\n•Compara ese valor con cada case.\n•Cuando encuentra un case que coincide, ejecuta sus instrucciones.\n•El break detiene la ejecución del switch."}] },
  { id: "j_for", categoria: "java", nombre: "for", palabrasClave: ["for"], tipo: "tecnico", definicion: "Bucle For.", codigos: [{titulo: "Contador", cuerpo: "for(int i=0; i<10; i++)", explicacion: "🔍 DESGLOSE DETALLADO:\n• es una estructura de control repetitiva que permite ejecutar un bloque de instrucciones varias veces."}, {titulo: "Foreach", cuerpo: "public class EjemploFor {\n\n   public static void main(String[] args) {\n\n     for (int i = 1; i <= 5; i++) {\n\n       System.out.println(i);\n\n     }\n\n   }\n\n})", explicacion: "🔍 DESGLOSE DETALLADO:\n• Recorre colección."}] },
  { id: "j_class", categoria: "java", nombre: "class", palabrasClave: ["class"], tipo: "tecnico", definicion: "Clase.", codigos: [{titulo: "Definición", cuerpo: "class Persona { }", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una estructura fundamental de la programación orientada a objetos."}, {titulo: "Pública", cuerpo: "public class Programa {\n\n   public static void main(String[] args) {\n\n     Persona p = new Persona();\n\n     p.nombre = \"Carlos\";\n\n     p.edad = 25;\n\n     System.out.println(p.nombre);}\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• representar entidades del mundo real\n• dividir programas grandes en partes más pequeñas\n• reutilizar código\n• crear aplicaciones complejas de forma organizada\n\nPor esta razón, Java está diseñado principalmente para trabajar con clases y objetos."}] },
  { id: "j_new", categoria: "java", nombre: "new", palabrasClave: ["new"], tipo: "tecnico", definicion: "Instanciar.", codigos: [{titulo: "Objeto", cuerpo: "class Auto {\n\n   String marca;\n\n}\n\npublic class Programa {\n\n   public static void main(String[] args) {\n\n     Auto a = new Auto();\n\n     a.marca = \"Toyota\";\n\n     System.out.println(a.marca);\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• es un operador que se utiliza para crear objetos a partir de una clase."}, {titulo: "Array", cuerpo: "public class EjemploArray {\n\n     public static void main(String[] args) {\n\n     int[] numeros = new int[5];\n\n     numeros[0] = 5;\n\n     numeros[1] = 10;\n\n     numeros[2] = 15;\n\n     numeros[3] = 20;\n\n     numeros[4] = 25;\n\n     for (int i = 0; i < 5; i++) {\n\n       System.out.println(numeros[i]);\n\n     }\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El operador new permite crear arreglos en Java reservando memoria para almacenar varios elementos del mismo tipo de dato."}] },
  { id: "j_inherit", categoria: "java", nombre: "inherit (Herencia)", palabrasClave: ["inherit", "extends"], tipo: "tecnico", definicion: "Reutilización de código.", codigos: [{titulo: "Clase Base", cuerpo: "class Animal {\n\n   void comer() {\n\n     System.out.println(\"Comiendo\");\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una característica fundamental de la programación orientada a objetos que permite crear nuevas clases basadas en clases existentes."}, {titulo: "Clase Derivada", cuerpo: "class Perro extends Animal {\n\n   void ladrar() {\n\n     System.out.println(\"Ladrando\");\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• La herencia en Java permite que una clase herede atributos y métodos de otra clase mediante la palabra clave extends. Esto facilita la reutilización de código y la creación de jerarquías de clases dentro de los programas."}] },
  { id: "j_exception", categoria: "java", nombre: "try / catch (Excepciones)", palabrasClave: ["try", "catch"], tipo: "tecnico", definicion: "Manejo de errores.", codigos: [{titulo: "Estructura Básica", cuerpo: "try {\n\n   // Código que puede lanzar excepción\n\n} catch (Exception e) {\n\n   // Manejo de la excepción\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una estructura de control que permite manejar errores o situaciones excepcionales que pueden ocurrir durante la ejecución de un programa."}, {titulo: "Ejemplo con división", cuerpo: "try {\n\n   int resultado = 10 / 0;\n\n} catch (ArithmeticException e) {\n\n   System.out.println(\"Error: División por cero\");\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• En este ejemplo, el código dentro del bloque try intenta realizar una división por cero, lo que genera una excepción de tipo ArithmeticException. El bloque catch captura esa excepción y maneja el error imprimiendo un mensaje en la consola."}] },
  { id: "j_thread", categoria: "java", nombre: "Thread (Hilos)", palabrasClave: ["thread", "run"], tipo: "tecnico", definicion: "Ejecución concurrente.", codigos: [{titulo: "Definición", cuerpo: "class MiHilo extends Thread {\n\n   public void run() {\n\n     System.out.println(\"Hilo en ejecución\");\n\n   }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Es una unidad de ejecución dentro de un programa que permite realizar tareas de manera concurrente."}, {titulo: "Iniciar Hilo", cuerpo: "MiHilo hilo = new MiHilo();\nhilo.start();", explicacion: "🔍 DESGLOSE DETALLADO:\n• Un Thread en Java es un hilo de ejecución que permite que un programa realice varias tareas de forma concurrente. Los hilos pueden crearse extendiendo la clase Thread o implementando la interfaz Runnable, y su ejecución comienza mediante el método start()."}] },
  { id: "j_lambda", categoria: "java", nombre: "Lambda (Funciones Anónimas)", palabrasClave: ["lambda"], tipo: "tecnico", definicion: "Funciones sin nombre.", codigos: [{titulo: "Sintaxis Básica", cuerpo: "public class Main {\n\n  public static void main(String[] args) {\n\n   Operacion suma = (a, b) -> a + b;\n\n   int resultado = suma.calcular(5, 3);\n\n   System.out.println(resultado);\n\n  }\n\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n•Las funciones Lambda son funciones anónimas que permiten definir comportamientos de manera simple y directa, utilizando la sintaxis (parámetros) -> expresión. Son muy utilizadas en Java moderno para simplificar el código y trabajar con programación funcional."}, {titulo: "Ejemplo con Listas", cuerpo: "import java.util.ArrayList;\n\npublic class Main {\n\n   public static void main(String[] args) {\n\n     ArrayList<String> lista = new ArrayList<>();\n\n       nombres.add(\"Ana\");\n       nombres.add(\"Luis\");\n       nombres.add(\"Pedro\");\n\n       nombres.forEach(nombre -> System.out.println(nombre));\n\n     }\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• Las expresiones Lambda aplicadas a listas permiten realizar operaciones sobre los elementos de una colección de manera más simple, clara y compacta, utilizando métodos como forEach() para recorrer los elementos sin necesidad de estructuras de repetición tradicionales."}] },
  
  

  // =================================================================================
  // 🐍 PYTHON (INTRODUCCIÓN COMPLETA + TEMAS)
  // =================================================================================
  { 
    id: "py_intro", 
    categoria: "python", 
    nombre: "Introducción a Python", 
    palabrasClave: ["python", "2"], 
    tipo: "concepto", 
    definicion: "🐍 ¿QUÉ ES PYTHON?\n\nPython es un lenguaje de alto nivel, interpretado y multiparadigma. Es conocido por su sintaxis extremadamente limpia y legible (casi como leer inglés). No requiere compilación previa, lo que lo hace ideal para prototipado rápido.\n\nCaracterísticas Clave:\n• Lenguaje interpretado:\n No necesita compilarse antes de ejecutarse; el intérprete ejecuta el código directamente.\n\n• Sintaxis simple y legible:\n Utiliza una estructura clara basada en indentación, lo que facilita la lectura del código\n\n• Multiparadigma:\n Permite programar usando diferentes estilos:\n    Programación estructurada\n    Programación orientada a objetos\n    Programación funcional\n\n• Gran cantidad de librerías:\nCuenta con muchas bibliotecas que permiten resolver problemas complejos sin tener que programarlo todo desde cero.\n\n• Portabilidad\n Los programas escritos en Python pueden ejecutarse en distintos sistemas operativos como Windows, Linux o macOS.", 
    codigos: [
      {titulo: "Hola Mundo", cuerpo: "print('Hola Python')", explicacion: "🔍 DESGLOSE DETALLADO:\n• print: Función nativa de salida.\n• Comillas: Pueden ser simples o dobles.\n• Sin punto y coma: Python usa saltos de línea."},
      {titulo: "Variables", cuerpo: "nombre = 'Ana'\nedad = 25", explicacion: "🔍 DESGLOSE DETALLADO:\n• Tipado Dinámico: No declaras el tipo.\n• Python deduce que 'nombre' es texto y 'edad' entero."}
    ] 
  },
  { id: "py_def", categoria: "python", nombre: "def (Función)", palabrasClave: ["def", "return"], tipo: "tecnico", definicion: "Definición de funciones.", codigos: [{titulo: "Función Simple", cuerpo: "def saludar():\n  print('Hola')", explicacion: "🔍 DESGLOSE DETALLADO:\n• def: Define la función.\n• (): Argumentos vacíos.\n• : (Dos puntos): Inicia bloque."},{titulo: "Con Retorno", cuerpo: "def suma(a, b):\n  return a + b\n    return resultado ", explicacion: "🔍 DESGLOSE DETALLADO:\n•La función suma recibe dos valores (a y b).\n•Realiza la operación de suma.\n• return: Entrega el resultado y sale.\n• El valor devuelto se guarda en la variable total."}]},
  { id: "py_print", categoria: "python", nombre: "print", palabrasClave: ["print"], tipo: "tecnico", definicion: "Función de salida.", codigos: [{titulo: "Salida Básica", cuerpo: "print('Hola Mundo')", explicacion: "🔍 DESGLOSE DETALLADO:\n• print es una función incorporada en Python que se utiliza para mostrar información en la consola o terminal. Permite imprimir texto, variables y resultados de expresiones, facilitando la comunicación con el usuario y la depuración del código."}]},
  { id: "py_input", categoria: "python", nombre: "input", palabrasClave: ["input"], tipo: "tecnico", definicion: "Función de entrada.", codigos: [{titulo: "Entrada Básica", cuerpo: "nombre = input('¿Cómo te llamas? ')", explicacion: "🔍 DESGLOSE DETALLADO:\n• input es una función incorporada en Python que se utiliza para recibir datos del usuario a través de la consola o terminal. Permite mostrar un mensaje al usuario y esperar a que este ingrese información, la cual se devuelve como una cadena de texto (string)."},{titulo: "Entrada Numérica", cuerpo: "edad = int(input('¿Cuántos años tienes? '))", explicacion: "🔍 DESGLOSE DETALLADO:\n• Para obtener un número, se envuelve input con int() para convertir la cadena ingresada a un entero."}]},
  { id: "py_str", categoria: "python", nombre: "str (Cadena)", palabrasClave: ["str"], tipo: "tecnico", definicion: "Texto entre comillas.", codigos: [{titulo: "Declaración", cuerpo: "mensaje = 'Hola'", explicacion: "🔍 DESGLOSE DETALLADO:\n• str es un tipo de dato en Python que se utiliza para representar texto. Las cadenas de texto se definen utilizando comillas simples (' ') o comillas dobles (\" \")."}, {titulo: "Concatenación", cuerpo: "nombre = 'Ana'\nsaludo = 'Hola ' + nombre\nprint(saludo)", explicacion: "🔍 DESGLOSE DETALLADO:\n• La concatenación de cadenas en Python se realiza utilizando el operador +, que une dos o más cadenas para formar una nueva cadena."}]},
  { id: "py_int", categoria: "python", nombre: "int (Entero)", palabrasClave: ["int"], tipo: "tecnico", definicion: "Número sin decimales.", codigos: [{titulo: "Declaración", cuerpo: "edad = 25", explicacion: "🔍 DESGLOSE DETALLADO:\n• int es un tipo de dato en Python que se utiliza para representar números enteros, es decir, números sin parte decimal."}, {titulo: "Operación", cuerpo: "x = 10 + 5", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo int en Python permite realizar operaciones matemáticas básicas como suma, resta, multiplicación y división entre números enteros."}]},
  { id: "py_float", categoria: "python", nombre: "float (Decimal)", palabrasClave: ["float"], tipo: "tecnico", definicion: "Número con decimales.", codigos: [{titulo: "Declaración", cuerpo: "pi = 3.14", explicacion: "🔍 DESGLOSE DETALLADO:\n• float es un tipo de dato en Python que se utiliza para representar números con parte decimal, es decir, números que pueden tener una fracción."}, {titulo: "Operación", cuerpo: "precio = 12.5\ndescuento = 2.0\nresultado = precio - descuento\nprint(resultado)", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo float en Python permite realizar operaciones matemáticas con números decimales, lo que es útil para cálculos financieros, científicos y cualquier situación donde se requiera precisión decimal."}]},
  { id: "py_bool", categoria: "python", nombre: "bool (Lógico)", palabrasClave: ["bool"], tipo: "tecnico", definicion: "Valor verdadero o falso.", codigos: [{titulo: "Declaración", cuerpo: "es_mayor = True\nes_menor = False", explicacion: "🔍 DESGLOSE DETALLADO:\n• bool es un tipo de dato en Python que se utiliza para representar valores lógicos, es decir, valores que pueden ser verdaderos (True) o falsos (False)."}, {titulo: "Condicional", cuerpo: "tiene_edad = True\ntiene_permiso = False\n\nif tiene_edad and tiene_permiso:\n   print(\"Puede entrar\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo bool es fundamental para el control de flujo en Python, ya que se utiliza en estructuras condicionales como if, while y for para tomar decisiones basadas en condiciones lógicas."}]},
  { id: "py_if", categoria: "python", nombre: "if / elif / else", palabrasClave: ["if", "elif", "else"], tipo: "tecnico", definicion: "Control de flujo condicional.", codigos: [{titulo: "Condición Básica", cuerpo: "if condicion:\n  edad = 18\n   if edad >= 18:\n     if edad >= 18:", explicacion: "🔍 DESGLOSE DETALLADO:\n• if: La instruccion if se utiliza para evaluar una condicion.\nSi la condicion es verdadera, se ejecuta el bloque de código dentro del if se ejecuta.\n• Indentación: Si la condición se cumple, el programa mostrará el mensaje."},{titulo: "Else", cuerpo: "numero = 0\n\nif numero > 0:\n   print(\"El número es positivo\")\nelif numero < 0:\n   print(\"El número es negativo\")\nelse:\n   print(\"El número es cero\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• El programa evaluará cada condición y mostrará el mensaje correspondiente.\n•Permiten controlar el flujo del programa.\n•Evalúan condiciones lógicas.\n•Pueden utilizar operadores relacionales como:\n <,  >, ==,  >=,  <=,  !=."},{titulo: "elif", cuerpo: "numero = 0\n\nif numero > 0:\n   print(\"El número es positivo\")\nelif numero < 0:\n   print(\"El número es negativo\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• elif: 'Else If' abreviado.\n•Aquí el programa revisa una segunda condición si la primera no es verdadera."}]},
  { id: "py_while", categoria: "python", nombre: "while", palabrasClave: ["while"], tipo: "tecnico", definicion: "Bucle While.", codigos: [{titulo: "Estructura Básica", cuerpo: "contador = 0\n\nwhile contador < 5:\n  print(contador)\n  contador += 1", explicacion: "🔍 DESGLOSE DETALLADO:\n• while contador < 5:\nEl programa ejecutará el bloque de código dentro del while mientras la condición contador < 5 sea verdadera.\n• contador += 1\nIncrementa el valor de contador en 1 en cada iteración para evitar un bucle infinito."}]},
  { id: "py_for", categoria: "python", nombre: "for (Bucle)", palabrasClave: ["for", "in"], tipo: "tecnico", definicion: "Bucle de iteración.", codigos: [{titulo: "Rango Numérico", cuerpo: "for i in range(5):\n  print(i)", explicacion: "🔍 DESGLOSE DETALLADO:\n• range(5): Crea secuencia 0,1,2,3,4.\n• i: Variable temporal.\nEs la palabra reservada que indica el inicio de un ciclo o bucle.\nSignifica que el programa va a repetir unn conjunto de instrucciones varias veces"},{titulo: "Iterar Lista", cuerpo: "for fruta in frutas:\n  print(fruta)", explicacion: "🔍 DESGLOSE DETALLADO:\n• in: Recorre cada elemento.\n• No usa índices manuales."}]},
  { id: "py_func", categoria: "python", nombre: "lambda (Funciones Anónimas)", palabrasClave: ["lambda"], tipo: "tecnico", definicion: "Funciones sin nombre.", codigos: [{titulo: "Sintaxis Básica", cuerpo: "suma = lambda a, b: a + b\n\nresultado = suma(5, 3)\n\nprint(resultado)", explicacion: "🔍 DESGLOSE DETALLADO:\n• lambda a, b: a + b\nDefine una función anónima que toma dos argumentos (a y b) y devuelve su suma.\n• suma(5, 3)\nLlama a la función lambda con los valores 5 y 3, lo que devuelve 8."}]},
  { id: "py_list", categoria: "python", nombre: "list (Listas)", palabrasClave: ["list", "append"], tipo: "tecnico", definicion: "Colección ordenada.",  codigos: [ {titulo: "Creación", cuerpo: "frutas = [\"manzana\", \"banana\", \"naranja\"]\n\nprint(frutas[0])", explicacion: "🔍 DESGLOSE DETALLADO:\n• [ ]: Define lista.\n• Mutable: Se puede cambiar."}, {titulo: "Agregar", cuerpo: "frutas.append(\"uva\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• .append(): Añade al final.\n• Modifica la lista original."}]  },
  { id: "py_set", categoria: "python", nombre: "set (Conjunto)", palabrasClave: ["set"], tipo: "tecnico", definicion: "Colección sin orden ni duplicados.", codigos: [{titulo: "Creación", cuerpo: "numeros = {1, 2, 3}", explicacion: "🔍 DESGLOSE DETALLADO:\n• { }: Define conjunto.\n• No permite duplicados."}, {titulo: "Agregar Elemento", cuerpo: "numeros.add(4)", explicacion: "🔍 DESGLOSE DETALLADO:\n• .add(): Agrega elemento al conjunto.\n• Si el elemento ya existe, no se agrega."}] },
  { id: "py_match", categoria: "python", nombre: "match (Switch)", palabrasClave: ["match", "case"], tipo: "tecnico", definicion: "Coincidencia de patrones (3.10+).",  codigos: [{titulo: "Por Valor", cuerpo: "dia = 3\n\nmatch dia:\n case 1: print('Lunes')\n case 2: print('Martes')\n case 3: print('Miércoles')\n case 4: print('Jueves')\n case 5: print('Viernes')\n case _: print('Dia no válido')", explicacion: "🔍 DESGLOSE DETALLADO:\n• match:La variable dia tiene el valor 3\nLa estructura match compara ese valor con cada case.\nCuando encuentra case 3, ejecuta la instrucción correspondiente."},{titulo: "Por Defecto", cuerpo: "match x:\n case _: print('Otro')", explicacion: "🔍 DESGLOSE DETALLADO:\n• case _: Captura todo (Default)."}]},
  { id: "py_tuple", categoria: "python", nombre: "tuple (Tuplas)", palabrasClave: ["tuple"], tipo: "tecnico", definicion: "Colección inmutable.", codigos: [{titulo: "Creación", cuerpo: "coordenadas = (10, 20)\n\nprint(coordenadas[0])", explicacion: "🔍 DESGLOSE DETALLADO:\n• ( ): Define tupla.\n• Inmutable: No se puede cambiar."}, {titulo: "Desempaquetado", cuerpo: "x, y = coordenadas\n\nprint(x)\nprint(y)", explicacion: "🔍 DESGLOSE DETALLADO:\n• Desempaquetado de tuplas permite asignar cada elemento a una variable de forma directa."}] },
  { id: "py_class", categoria: "python", nombre: "class (Clases)", palabrasClave: ["class", "self"], tipo: "tecnico", definicion: "Programación Orientada a Objetos.", codigos: [{titulo: "Definición", cuerpo: "class Persona:\n  nombre = 'Juan'\n  edad = 20\n   persona1 = Persona()\n   print(persona1.nombre)", explicacion: "🔍 DESGLOSE DETALLADO:\n• class: Define objeto.\n• Permiten organizar mejor el código\n• Facilitan la reutilización de estructuras.\n• Permiten crear múltiples objetos con las mismas características.\n• Son la base de la programación orientada a objetos."},{titulo: "Método", cuerpo: "def hablar(self):\n  print('Hola')", explicacion: "🔍 DESGLOSE DETALLADO:\n• self: Referencia al propio objeto.\n• Obligatorio en métodos."}]},
  { id: "py_async", categoria: "python", nombre: "async / await", palabrasClave: ["async", "await"], tipo: "tecnico", definicion: "Código asíncrono.", codigos: [{titulo: "Definir Corutina", cuerpo: "async def saludo():\n   print(\"Hola desde una función asincrónica\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• async: Esta función se define como asincrónica, lo que permite que pueda ejecutarse junto con otras tareas sin bloquear el programa."},{titulo: "Esperar", cuerpo: "import asyncio\n\async def esperar():\n    print(\"Esperando...\")\n    await asyncio.sleep(2)\n    print(\"Han pasado 2 segundos\")", explicacion: "🔍 DESGLOSE DETALLADO:\n• async def esperar()\nDefine una función asincrónica llamada esperar.\n• print(\"Esperando...\")\nMuestra un mensaje antes de iniciar la espera.\n• await asyncio.sleep(2)\nEl programa espera 2 segundos, pero sin bloquear otras tareas del sistema.\n• print(\"Han pasado 2 segundos\")\nSe ejecuta después de que termina la espera."}] },
  { id: "py_dict", categoria: "python", nombre: "dict (Diccionarios)", palabrasClave: ["dict"], tipo: "tecnico", definicion: "Colección de pares clave-valor.", codigos: [{titulo: "Creación", cuerpo: "persona = {\"nombre\": \"Ana\", \"edad\": 25}\n\nprint(persona[\"nombre\"])", explicacion: "🔍 DESGLOSE DETALLADO:\n• persona es el nombre del diccionario.\n• \"nombre\", \"edad\" y \"ciudad\" son claves."}, {titulo: "Agregar Elemento", cuerpo: "persona[\"ciudad\"] = \"Madrid\"", explicacion: "🔍 DESGLOSE DETALLADO:\n• Se agrega una nueva clave 'ciudad' con su valor 'Madrid' al diccionario persona."}] },


 // =================================================================================
  // 🚀 C++ (INTRODUCCIÓN COMPLETA + TEMAS)
  // =================================================================================
  { 
    id: "cpp_intro", 
    categoria: "cpp", 
    nombre: "Introducción a C++", 
    palabrasClave: ["cpp", "c++", "3"], 
    tipo: "concepto", 
    definicion: "🚀 ¿QUÉ ES C++? 1ª Edicion C++ Manual teórico-práctico Autor Alan D. Osorio Rojas \n\nC++ es un lenguaje compilado de alto rendimiento y propósito general. Es la evolución directa del lenguaje C, añadiendo orientación a objetos. Te da control total sobre el hardware, especialmente la memoria (RAM), lo que lo hace inigualable en velocidad.\n\nCaracterísticas Clave:\n• Gestión Manual de Memoria: Usas punteros y referencias para optimizar al máximo.\n• Compilado: Se traduce a código máquina (binario) directamente.\n• Usos: Motores de videojuegos (Unreal Engine), Sistemas Operativos, Drivers y Sistemas Financieros de alta frecuencia.", 
    codigos: [
    {titulo: "Estructura Main", cuerpo: "int main() {\n  return 0;\n}", explicacion: "🔍 DESGLOSE DETALLADO:\n• main: Punto de entrada.\n• return 0: Éxito al SO."},
    {titulo: "Salida Consola", cuerpo: "std::cout << \"Hola\";", explicacion: "🔍 DESGLOSE DETALLADO:\n• cout: Console Out.\n• <<: Operador de inserción para enviar datos a la pantalla."}
    ]},
    
    { id: "cpp_types", categoria: "cpp", nombre: "int / char / bool", palabrasClave: ["int", "char", "float", "bool"], tipo: "tecnico", definicion: "Tipos fundamentales.",  codigos: [ {titulo: "Entero", cuerpo: "#include <iostream> \n using namespace std; \n  int main () {\n int edad = 20;\n cout <<\"edad \"<<edad;\n return 0;}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo de dato int se utiliza para almacenar números enteros, es decir, números sin parte decimal..\n• Se usa para guardar valores como: edades, contadores, cantidades"}, {titulo: "Carácter", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n  char letra = 'A';\n return 0;}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo de dato char se utiliza para almacenar un solo carácter, que puede ser una letra, un dígito, un símbolo o cualquier otro carácter definido en el estándar Unicode."}, {titulo: "Booleano", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n  bool flag = true;\n return 0;}", explicacion: "🔍 DESGLOSE DETALLADO:\n• El tipo de dato bool se utiliza para almacenar valores lógicos, es decir, valores que solo pueden ser:\n• true (verdadero) o false (falso)\n"}  ]},
    { id: "cpp_if", categoria: "cpp", nombre: "if / else", palabrasClave: ["if", "else"], tipo: "tecnico", definicion: "Control condicional.",  codigos: [ {titulo: "if", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n int edad = 18;\n if (edad >= 18) {cout << \"Eres mayor de edad\" << endl;} return 0;}", explicacion: "Ejecuta código si la condición es verdadera." }, { titulo: "else", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n int edad = 17;\n if (edad >= 18) {cout << \"Eres mayor de edad\" << endl;} else {cout << \"No eres mayor de edad\" << endl;} return 0;}", explicacion: "Ejecuta código si la condición es falsa." } ]},
    { id: "cpp_loop", categoria: "cpp", nombre: "for / while", palabrasClave: ["for", "while"], tipo: "tecnico", definicion: "Bucles.",  codigos: [ {titulo: "for", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n for (int i = 1; i <= 5; i++) {cout << i << endl;} return 0;}", explicacion: "Bucle que repite código un número definido de veces." }, {titulo: "while", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n int x = 5;\n while (x > 0) {cout << x << endl; x--;} return 0;}", explicacion: "Bucle que se ejecuta mientras la condición sea verdadera." }  ]},
    { id: "cpp_class", categoria: "cpp", nombre: "class / struct", palabrasClave: ["class", "struct"], tipo: "tecnico", definicion: "Objetos.",  codigos: [ {titulo: "class", cuerpo: "#include <iostream>\n using namespace std;\n class Persona {\n public:\n int edad;\n };\n int main() {\n Persona p;\n p.edad = 20;\n cout << p.edad;\n return 0;};", explicacion: "Define una clase para crear objetos." },{titulo: "struct", cuerpo: "#include <iostream>\n using namespace std;\n struct Alumno {\n int edad;\n };\n int main() {\n Alumno a;\n a.edad = 20;\n cout << a.edad;\n return 0;};", explicacion: "Estructura que agrupa variables." }]},
    { id: "cpp_template", categoria: "cpp", nombre: "template", palabrasClave: ["template", "typename"], tipo: "tecnico", definicion: "Genéricos.", codigos: [{titulo: "template", cuerpo: "#include <iostream> \n using namespace std;\n template <typename T>\n T suma(T a, T b) ) { return a + b;}\n int main() { \n cout << suma(3, 4);return 0; } {", explicacion: "Permite crear funciones o clases que funcionan con diferentes tipos de datos." }]},
    { id: "cpp_float_double", categoria: "cpp",nombre: "double ", palabrasClave: ["float", "double"], tipo: "tecnico",definicion: "Tipos de datos para números con decimales.",codigos: [{titulo: "float", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n float precio = 19.99;\n cout << precio;\n return 0; };", explicacion: "Tipo de dato para números decimales con menor precisión."},{titulo: "double", cuerpo: "#include <iostream>\n using namespace std;\n int main() {\n double numero = 3.14159;\n cout << numero;\n return 0; };", explicacion: "Tipo de dato para números decimales con mayor precisión que float."}]},  
    { id: "cpp_char_string", categoria: "cpp", nombre: "char", palabrasClave: ["char", "string"], tipo: "tecnico",definicion: "Tipos de datos para caracteres y texto.",codigos: [{titulo: "char", cuerpo: "char letra = 'A';", explicacion: "Tipo de dato que almacena un solo carácter."},]}, 
    { id: "cpp_switch", categoria: "cpp", nombre: "switch", palabrasClave: ["switch"],tipo: "tecnico",definicion: "Estructura de control para evaluar múltiples casos.",codigos: [{titulo: "switch", cuerpo: " #include <iostream>\nusing namespace std;\n\nint main() {\n  int opcion = 2;\n\n  switch(opcion) {\n    case 1:\n      cout << 'Opcion 1';\n      break;\n\n    case 2:\n      cout << 'Opcion 2';\n      break;\n\n    default:\n      cout << 'Otra opcion';\n  }\n\n  return 0;\n}}", explicacion: "Permite ejecutar diferentes bloques dependiendo del valor de una variable."}]},
 // =================================================================================
  // 🌐 HTML (INTRODUCCIÓN COMPLETA + TEMAS)
  // =================================================================================
  { 
    id: "html_intro", 
    categoria: "html", 
    nombre: "Introducción a HTML", 
    palabrasClave: ["html", "4"], 
    tipo: "concepto",
    definicion: "🌐 HTML5, CSS Y JAVASCRIPT  1ª Edición de los Autores LUJÁN CASTILLO, José Dimas\n\nHTML (HyperText Markup Language) es el lenguaje de marcado estándar utilizado para crear páginas web. Su función principal es definir la estructura y el contenido de un documento en la web.\nHTML utiliza etiquetas (tags) para indicar al navegador cómo debe organizar y mostrar los elementos de una página, como textos, imágenes, enlaces, tablas o formularios.\n\nCaracterísticas Clave:\n\n•Uso de Etiquetas: HTML utiliza etiquetas (tags) para definir los diferentes elementos de una página web. Las etiquetas normalmente se escriben en pares: una de apertura y una de cierre.\n\n•Semántica: La semántica en HTML permite que las etiquetas indiquen el significado del contenido, no solo su apariencia. La etiqueta <article> indica que el contenido es una pieza independiente de información, como una noticia o publicación.\n\n•DOM: Cuando el navegador carga una página web, analiza el código HTML y lo convierte en una estructura que permite acceder, modificar o eliminar elementos de la página mediante programación, normalmente con JavaScript.", 
    codigos: [{titulo: "Documento", cuerpo: "<!DOCTYPE html>", explicacion: "🔍 DESGLOSE DETALLADO:\n• Define estándar HTML5.\n• Primera línea obligatoria."}, {titulo: "Raíz", cuerpo: "<html lang='es'>...</html>", explicacion: "🔍 DESGLOSE DETALLADO:\n• Envuelve todo.\n• lang: Idioma para buscadores."}] },
    { id: "h_div", categoria: "html", nombre: "div / span", palabrasClave: ["div", "span"], tipo: "tecnico", definicion: "Contenedores.", codigos: [{titulo: "Div (Bloque)", cuerpo: "<div>\n   <h2>Noticias</h2>\n   <p>Este es un párrafo dentro de un contenedor div.</p>\n  </div>", explicacion: "🔍 DESGLOSE DETALLADO:\n• Elemento de bloque.\n• Salto de línea auto.\n• Estructura principal."},{titulo: "Span (Línea)", cuerpo: "<span>Texto</span>", explicacion: "🔍 DESGLOSE DETALLADO:\n• Elemento en línea.\n• Sin salto.\n• Para estilos finos."}] },
    { id: "h_img", categoria: "html", nombre: "img (Imagen)", palabrasClave: ["img"], tipo: "tecnico", definicion: "La etiqueta <img> se utiliza en HTML para insertar imágenes dentro de una página web Las imágenes pueden ser archivos almacenados localmente en el sitio web o recursos ubicados en internet.", codigos: [ {titulo: "Local", cuerpo: "<img src=\"paisaje.jpg\" alt=\"Paisaje de montaña\" width=\"300\">", explicacion: "🔍 DESGLOSE DETALLADO:\n• src: El atributo src (source) indica la ruta o dirección de la imagen que se desea mostrar. \n• La etiqueta <img> es una etiqueta vacía, lo que significa que no tiene etiqueta de cierre y su funcionamiento depende de los atributos que se le agreguen. \n •La etiqueta <img> permite mostrar imágenes en una página web, utilizando principalmente los atributos src para indicar la ubicación del archivo y alt para describir el contenido de la imagen."},{titulo: "Accesible", cuerpo: "<img src=\"perro.jpg\" alt=\"Perro corriendo en el parque\">", explicacion: "🔍 DESGLOSE DETALLADO:\n•El atributo alt (texto alternativo) proporciona una descripción de la imagen.\n•SEO: Ayuda a los buscadores a entender el contenido de la imagen."}]  },
    { id: "h_link", categoria: "html", nombre: "a (Enlace)", palabrasClave: ["a"], tipo: "tecnico", definicion: "Hipervínculos.", codigos: [{titulo: "Interno", cuerpo: "<a href='pag2.html'>Ir</a>", explicacion: "🔍• La etiqueta <a> se utiliza en HTML para crear hipervínculos, es decir, enlaces que permiten navegar entre diferentes páginas web, documentos o recursos en internet.\n • Los enlaces son una de las características fundamentales de la web, ya que permiten conectar información entre diferentes páginas.\n • El atributo href (Hypertext Reference) indica la dirección o destino del enlace."},{titulo: "Externo", cuerpo: "<a href=\"https://www.google.com\" target=\"_blank\">Abrir Google</a>", explicacion: "🔍 DESGLOSE DETALLADO:\n• El atributo target se utiliza en la etiqueta <a> para indicar dónde se abrirá el enlace cuando el usuario haga clic en él.\n• Este atributo permite controlar si el enlace se abrirá en la misma página, en una nueva pestaña o en otro contexto del navegador."}] },
    { id: "h_input", categoria: "html", nombre: "input (Entrada)", palabrasClave: ["input"], tipo: "tecnico", definicion: "Entradas.", codigos: [{titulo: "Texto", cuerpo: "<input type='text'>", explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <input> se utiliza en HTML para crear campos donde el usuario puede introducir datos dentro de un formulario.\n• Estos campos permiten recopilar información como texto, contraseñas, correos electrónicos, números, entre otros.."},{titulo: "Password", cuerpo: "<input type='password'>", explicacion: "🔍 DESGLOSE DETALLADO:\n• El atributo type indica el tipo de información que el usuario debe ingresar.\n• Type se utiliza en la etiqueta <input> para definir el tipo de dato que el usuario debe ingresar en un campo de formulario."}] }, { id: "h_form", categoria: "html", nombre: "form (Formulario)", palabrasClave: ["form"], tipo: "tecnico", definicion: "Formulario.", codigos: [ {titulo: "Estructura", cuerpo: "<form action='/send'>", explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <form> se utiliza en HTML para crear formularios que permiten recopilar información de los usuarios en una página web.\n •Dentro de un formulario se colocan diferentes elementos de entrada, como:\n •campos de texto (input)\n •botones (button)\n •listas desplegables\n •casillas de selección"},{titulo: "Botón", cuerpo: "<button type='submit'>", explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <button> se utiliza para crear botones interactivos en una página web.\n• Los botones pueden utilizarse para enviar formularios, ejecutar scripts de JavaScript o realizar acciones dentro de la página."}]  },{ id: "h_list", categoria: "html", nombre: "ul / ol / li", palabrasClave: ["ul", "ol", "li"], tipo: "tecnico", definicion: "Listas.", codigos: [{titulo: "Puntos", cuerpo: "<ul><li>Item</li></ul>", explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <ul> se utiliza para crear listas sin orden específico.\n• Los elementos se muestran generalmente con viñetas o puntos."},{titulo: "Números", cuerpo: "<ol><li>Item</li></ol>", explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <ol> se usa para crear listas ordenadas, donde los elementos aparecen numerados.\n• Secuencia 1, 2, 3."},{titulo: "Elementos de la lista (Li)", cuerpo: "<ol><li>Item</li></ol>",  explicacion: "🔍 DESGLOSE DETALLADO:\n• La etiqueta <li> se utiliza para crear elementos dentro de una lista.\n• Puede usarse dentro de <ul> o <ol>."}] },
  
];